cmake_minimum_required(VERSION 4.0)
project(COS1020___C___Programming)

set(CMAKE_CXX_STANDARD 14)

add_executable(COS1020___C___Programming
        "01. Intro to C++ Programming/01. Miles to Kilometers Converter.cpp"
        "01. Intro to C++ Programming/02. Celsius to Fahrenheit Converter.cpp"
        "01. Intro to C++ Programming/03. Kilometers to Miles Converter.cpp"
        "02. Fundamental Data Types/01. Pennies and Nickels.cpp"
        "02. Fundamental Data Types/02. Circle Perimeter and Area.cpp"
        "02. Fundamental Data Types/03. Calculator.cpp"
        "02. Fundamental Data Types/04. Pounds to Kilograms Converter.cpp"
        "02. Fundamental Data Types/05. Greeter.cpp"
        "02. Fundamental Data Types/06. Expression.cpp"
        "02. Fundamental Data Types/07. 25% Discount.cpp"
        "02. Fundamental Data Types/08. Total Cost of Apples.cpp"
        "02. Fundamental Data Types/09. Expression II.cpp"
        "02. Fundamental Data Types/10. Pennies, Nickels, Dimes, and Quarters.cpp"
        "03. Decision Statements/01. Weekly Salary Calculator.cpp"
        "03. Decision Statements/02. Total Product Price.cpp"
        "03. Decision Statements/03. Leap Year.cpp"
        "04. Loops/01. Temperatures Table.cpp"
        "04. Loops/02. Average Calculator.cpp"
        "04. Loops/03. N x N Asterisks Table.cpp"
        "04. Loops/04. Fibonacci Sequence.cpp"
        "04. Loops/05. Triangle of Asterisks.cpp"
        "05. Functions/01. Pythagorean Traingle Hypotenuse Calculator.cpp"
        "05. Functions/02. Perimeter and Area of a Rectangle.cpp"
        "05. Functions/03. Pay Raise Calculator.cpp"
        "05. Functions/04. Factorial.cpp"
        "05. Functions/05. Sum of Evens in a Range.cpp"
        "05. Functions/06. Maximum Integer.cpp"
        "06. Simple Data Types/01. Uppercase Characters Extractor.cpp"
        "06. Simple Data Types/02. Product Enum.cpp"
        "07. Arrays and Structs/01. Average of an Int Array.cpp"
        "07. Arrays and Structs/02. Positive Int Array Elements Counter.cpp"
        "07. Arrays and Structs/03. Sum of Odd Array Elements.cpp"
        "07. Arrays and Structs/04. 10x10 Matrix Multiplication Table.cpp"
        "07. Arrays and Structs/05. Person Struct.cpp"
        "08. Strings/01. Verical Display of C-Style String.cpp"
        "08. Strings/02. Length of C-Style String.cpp"
        "08. Strings/03. Valid Name Checker with C-Style String.cpp"
        "09. Recursion/01. Recursive Multiplication.cpp"
        "09. Recursion/02. Recursive Palindrome Checker.cpp"
        "10. Streams and Files/01. Names Saver.cpp"
        "10. Streams and Files/02. Character Counter.cpp"
        "10. Streams and Files/03. Numbers' Statistics.cpp"
        "10. Streams and Files/04. Copier.cpp"
        "11. Pointers/01. Swap with Pointers.cpp"
        "11. Pointers/02. Swap with References.cpp"
        "11. Pointers/03. Print Array.cpp"
        "12. Intro to OOP/01. Divider/Divider.cpp"
        "12. Intro to OOP/01. Divider/Divider.h"
        "12. Intro to OOP/01. Divider/main.cpp"
        "12. Intro to OOP/02. Circle/Circle.cpp"
        "12. Intro to OOP/02. Circle/Circle.h"
        "12. Intro to OOP/02. Circle/main.cpp"
        "12. Intro to OOP/03. Student/Student.cpp"
        "12. Intro to OOP/03. Student/Student.h"
        "12. Intro to OOP/03. Student/main.cpp"
        "12. Intro to OOP/04. Triangle/Triangle.cpp"
        "12. Intro to OOP/04. Triangle/Triangle.h"
        "12. Intro to OOP/04. Triangle/main.cpp"
        "12. Intro to OOP/05. Point/Point.cpp"
        "12. Intro to OOP/05. Point/Point.h"
        "12. Intro to OOP/05. Point/main.cpp"
        "13. Inheritance and Polymorphism/01. Students and Instructors/Person.cpp"
        "13. Inheritance and Polymorphism/01. Students and Instructors/Person.h"
        "13. Inheritance and Polymorphism/01. Students and Instructors/Student.cpp"
        "13. Inheritance and Polymorphism/01. Students and Instructors/Student.h"
        "13. Inheritance and Polymorphism/01. Students and Instructors/Instructor.cpp"
        "13. Inheritance and Polymorphism/01. Students and Instructors/Instructor.h"
        "13. Inheritance and Polymorphism/01. Students and Instructors/main.cpp"
        "13. Inheritance and Polymorphism/02. Fruits/Fruit.cpp"
        "13. Inheritance and Polymorphism/02. Fruits/Fruit.h"
        "13. Inheritance and Polymorphism/02. Fruits/Apple.cpp"
        "13. Inheritance and Polymorphism/02. Fruits/Apple.h"
        "13. Inheritance and Polymorphism/02. Fruits/Grapefruit.cpp"
        "13. Inheritance and Polymorphism/02. Fruits/Grapefruit.h"
        "13. Inheritance and Polymorphism/02. Fruits/main.cpp"
        "13. Inheritance and Polymorphism/03. Shapes/Shape.cpp"
        "13. Inheritance and Polymorphism/03. Shapes/Shape.h"
        "13. Inheritance and Polymorphism/03. Shapes/Square.cpp"
        "13. Inheritance and Polymorphism/03. Shapes/Square.h"
        "13. Inheritance and Polymorphism/03. Shapes/Rectangle.cpp"
        "13. Inheritance and Polymorphism/03. Shapes/Rectangle.h"
        "13. Inheritance and Polymorphism/03. Shapes/main.cpp"
        "14. Templates/01. Minimum Array Element.cpp"
        "14. Templates/02. Tuple/Tuple.cpp"
        "14. Templates/02. Tuple/Tuple.h"
        "14. Templates/02. Tuple/main.cpp"
        "15. Operator Overloading/01. Employee/Employee.cpp"
        "15. Operator Overloading/01. Employee/Employee.h"
        "15. Operator Overloading/01. Employee/main.cpp"
        "15. Operator Overloading/02. Location/Location.cpp"
        "15. Operator Overloading/02. Location/Location.h"
        "15. Operator Overloading/02. Location/main.cpp")
